#index:
#    path: /
#    controller: App\Controller\DefaultController::index
test_protected:
    path: /api/test
    controller: App\Controller\TestController::testProtected

test_public:
    path: /api/public/test
    controller: App\Controller\TestController::testPublic

test_personManager:
    path: /api/public/testPersonManager
    controller: App\Controller\TestController::testPersonManager

uloc_api:
    resource: '@UlocApiBundle/Resources/config/routes.xml'
    prefix: '/api'
